resources:
- name: repo
  type: git
  source:
    uri: https://github.com/yonlu/concourse-ci.git
    branch: main
    git_config:
    - name: safe.directory
      value: /tmp/build/get

# Test
jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      outputs:
      - name: the-artifact
      run:
        path: echo
        args: ["Hello World!"]
